version: "3"
services:
  postgres:
    image: postgres:11.14-alpine
    container_name: demo2-pg
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: jeet.patel@tntra.io
      PGADMIN_DEFAULT_PASSWORD: Start!23
    restart: always

volumes:
  pg_data:
